### ISSUE TITLE
Hash and Array accessors don't seem to be defined

### ISSUE THREAD

**Issue by esb** [devmynd/jsonb_accessor#25]
When the :hstore and :array types are used, the standard methods for accessing these data types don't seem to update the backing jsonb attributes.

For example, a :string_array attribute doesn't get updated after using '<<' methods.

test_array << 'new element'

Only total replacement using the '=' method is possible.

**Comment by crismali** [comment]
It looks like Rails is cloning values set via the `attribute` api so methods that mutate the values you set after setting them won't have any affect. Unfortunately this is a pretty tricky problem to solve. The first idea that comes to mind is to wrap any sort of collection value in some type of object that knows how to essentially set itself on the model it belongs to. That could be very surprising behavior though, ie you've explicitly specified you want an integer array and now you have something that isn't a normal array. 

This is similar to an issue I've run into in Rails when using an array field where mutating the array doesn't trigger an `attribute_will_change!` on the model. If Rails baked something in to address this issue it'd be fairly easy to add on our end. I'd be interested to see a pull request that implements this behavior for jsonb_accessor, but I have some reservations about it. I do agree that mutating the collection objects should update the model. 

As far as short term work arounds go, I don't believe there's a way to avoid using the setter. You could use the hash or array, mutate them, and then reset them at the end to avoid using the setter a bunch of times. I think for now that's about as close as we can get to the desired behavior.

**Comment by esb** [comment]
I've discovered that the built-in store_accessor doesn't have this issue, so maybe there are some clues in that code on how to get around this.

One of the nice things to be able to do is to define hash an array accessors that returned a default {} or [] instead of nil, so that you could use syntax such as 'obj.test_array << 123', rather than 'obj.test_array ||= []; obj.test_array << 123'.

**Comment by crismali** [comment]
> I've discovered that the built-in store_accessor doesn't have this issue, so maybe there are some clues in that code on how to get around this.

I'll definitely look into that.

> One of the nice things to be able to do is to define hash an array accessors that returned a default {} or [] instead of nil

I think that is part of a larger discussion around how setting defaults should work. This has been discussed a bit on a similar project called [HstoreAccessor](https://github.com/devmynd/hstore_accessor) [here](https://github.com/devmynd/hstore_accessor/issues/7). I've opened a separate issue for default values [here](https://github.com/devmynd/jsonb_accessor/issues/28).

**Comment by jhirn** [comment]
`<<` is actually a problem with plain old arrays as well. If you define an array column type (not json, just standard postgres array) shoveling onto the array will not update the array inside of the model. Since we are piggybacking on most of the ActiveRecord behavior it's not surprising shovel doesn't work on an array inside of a json column.

**Comment by crismali** [comment]
Closing this for now. I like the idea of this feature a lot but it seems like a lot to implement and maintain. Might revisit after the 1.0 release.
