### ISSUE TITLE
Jsonb_accessor does not override parent methods

### ISSUE THREAD

**Issue by Aevin1387** [devmynd/jsonb_accessor#29]
If you use jsonb_accessor on a subclass, and use it to override a method on a parent class, it does not override the method. See https://github.com/Aevin1387/jsonb-test for an example

**Comment by crismali** [comment]
Still trying to work out why this happens, but in the mean time here's a workaround:

```ruby
def getter_that_should_work
  read_attribute(__method__)
end
```

**Comment by Aevin1387** [comment]
A minor inconvenience for now, but that works.

**Comment by crismali** [comment]
[v1.0](https://github.com/devmynd/jsonb_accessor/releases/tag/v1.0.0.beta) leans heavily on the `attribute` API in ActiveRecord 5 and this inheritance issue seems to be a problem there as well. Hopefully it'll get fixed over there.
