### ISSUE TITLE
Annotate gem issue

### ISSUE THREAD

**Issue by kapso** [devmynd/jsonb_accessor#31]
Looks like Annotate gem (https://github.com/ctran/annotate_models) annotates jsonb accessor fields as well, along with the `jsonb` column? Is that expected.

So in the following case, 2 fields get annotated - `:data, :name, :age`

```ruby
jsonb_accessor :data,
        name: :string,
        age: :integer
```

**Comment by crismali** [comment]
It looks like Annotate is just reading out of the attributes without actually figuring out if the given attribute is a column. 

I think you could make a case either way. They're not in the table so they shouldn't be annotated but by using JsonbAccessor we're saying that while `name` or `age` aren't columns in the table that we do want to treat them in a similar way. 

In the end I'd say this is a bit weird, but not weird enough for us to walk away from the attribute API (it provides us with dirty tracking and lots of other good ActiveRecord-y methods).
