### ISSUE TITLE
Selecting specific fields fails

### ISSUE THREAD

**Issue by kapso** [devmynd/jsonb_accessor#32]
Given the following class...

```ruby
class User
  jsonb_accessor :preferences,
     send_email: :boolean
end
```

If I try this `User.select(:id, :name).find(8)` I get the following error

`ActiveModel::MissingAttributeError: missing attribute: preferences`

**Comment by crismali** [comment]
@kapso which version of ActiveRecord/JsonbAccessor are you finding this issue in?

**Comment by kapso** [comment]
Rails 4.2.4 and latest jsonb_accessor 0.3.0

**Comment by crismali** [comment]
29ff0d5 should take care of this. I'll ping you when it's released.

**Comment by kapso** [comment]
Great, any update on https://github.com/devmynd/jsonb_accessor/issues/33 since thats more critical for us. Thanks

**Comment by crismali** [comment]
@kapso Just released a new version with the fix for this (https://github.com/devmynd/jsonb_accessor/releases/tag/v0.3.1)

**Comment by kapso** [comment]
Thanks for the quick fix, unfortunately cannot use this gem due to #33 -- breaks our queries.
