### ISSUE TITLE
Active record query issue

### ISSUE THREAD

**Issue by kapso** [devmynd/jsonb_accessor#33]
Given the following object...

```ruby
class User
  jsonb_accessor :preferences,
     send_email: :boolean
end
```

When I try to run this query `Address.include(:user).order("users.name")`  rails will include `send_email` column in the `select` clause of the query, so something like this ....

`select "users"."send_email"`  ...which is obviously an error.

**Comment by crismali** [comment]
@kapso Which version of ActiveRecord and JsonbAccessor are you using?

**Comment by kapso** [comment]
Rails 4.2.4 and latest jsonb_accessor 0.3.0

**Comment by crismali** [comment]
@kapso I've added spec [here](https://github.com/devmynd/jsonb_accessor/blob/master/spec/jsonb_accessor_spec.rb#L1144). It looks like the example you've provided above but it does not fail. Is there something missing from the test?

**Comment by kapso** [comment]
I think this will fail, basically use order field from the join table. So not `products.id` but `product_category.id`

`Product.includes(:product_category).order("product_category.id").to_a`

**Comment by kapso** [comment]
@crismali 

When Rails early loads via join, its select individual fields and includes jsonb_accessor fields, thus error'ing out.

When Rails lazy loads, all it does is `select *` and it works.

**Comment by crismali** [comment]
Ah, I see. Taking a look.

**Comment by crismali** [comment]
At the moment this appears to be more of a bug with the ActiveRecord [`attribute`](http://edgeapi.rubyonrails.org/classes/ActiveRecord/Attributes/ClassMethods.html#method-i-attribute) api. I'm able to reproduce the error in classes without `jsonb_accessor` like so:

```ruby
class Product < ActiveRecord::Base
  belongs_to :product_category
end

class ProductCategory < ActiveRecord::Base
  attribute "foo", ActiveRecord::Type::Value
  has_many :products
end

Product.includes(:product_category).order("product_categories.id").to_a
# raises:
# PG::UndefinedColumn: ERROR:  column product_categories.foo does not exist
#      LINE 1: ...S t1_r0, "product_categories"."options" AS t1_r1, "product_c...
#                                                                    ^
```

**Comment by kapso** [comment]
Got it. So looks like until ActiveRecord issue is fixed, `jsonb_accessor` will not be usable with eager load joins?

**Comment by crismali** [comment]
Looks to be the case for now. For now I'm gonna check to see if there's already an open issue in the Rails repo.

**Comment by kapso** [comment]
@crismali any update on the Rails side?

**Comment by crismali** [comment]
We've been looking into it but currently don't have a work around.

**Comment by mockdeep** [comment]
We ran into this issue, too. Doesn't look like there's an issue open on rails around this.

**Comment by crismali** [comment]
This seems to work in Rails 5. [v0.4.0.beta](https://github.com/devmynd/jsonb_accessor/tree/22f003dc4f8ce62b08ce4f4f1347a99e87e78c74#rails-5) of this gem has support for Rails 5 now.
