### ISSUE TITLE
JRuby compatibility

### ISSUE THREAD

**Issue by ginkel** [devmynd/jsonb_accessor#35]
Hello,

I was wondering whether there are any plans to make this gem compatible with JRuby. I already started some work in https://github.com/LIQIDTechnology/jsonb_accessor/tree/jruby by conditionally adding JRuby dependencies, but that alone does not seem to be sufficient to achieve compatibility as the `activerecord-jdbc-adapter` seems to be confused by the model metadata injected by a `jsonb_accessor`:

Let's say, you have a model that has a jsonb attribute (and accessor) `data` that in turn has attributes `a` and `b`. This will cause ActiveRecord to issue queries like `SELECT models.data, models.a, models.b FROM models` when fetching models. If that helps I can also try getting the exact error message, but I hit the issue some time ago and forgot to keep an exact note.

Thanks,
Thilo

**Comment by crismali** [comment]
The selecting of jsonb defined attributes is a general problem with using virtual attributes in ActiveRecord (mentioned in #33). 

I agree though that JRuby support should be more explicit and that we should add it to travis.

**Comment by crismali** [comment]
We now support Rails 5 where this doesn't appear to be a problem anymore (note: https://github.com/devmynd/jsonb_accessor/tree/22f003dc4f8ce62b08ce4f4f1347a99e87e78c74#rails-5)
