### ISSUE TITLE
Inheritance error

### ISSUE THREAD

**Issue by boriscy** [devmynd/jsonb_accessor#39]
The inherited class generates an error ` warning: already initialized constant JsonbAccessor::JAMovement::JAExtras` if you defined on parent class **jsonb_accessor**

```ruby
class Movement
  jsonb_accessor :extras, inventory: true, balance: :decimal
end

class Income < Movement
end
```

In this case the `Income.new` will throw the exception

**Comment by jhirn** [comment]
Hi Boris!

I couldn't recreate this error.  Your example has a couple of issues. 

-Movement doesn't extend ActiveRecord::Base.

**Comment by boriscy** [comment]
I will create code to help u see. Sorry on the errors. `inventory: :boolean` and in my case it's of course extended from ActiveRecord::Base

**Comment by jhirn** [comment]
Thanks. 

I've written the folowing test which doesn't have an exception or warning. 

```
context "inheritance" do
      let(:sub_class) { Class.new(Product) }
      before { stub_const("Foo", sub_class) }
      after { JsonbAccessor.send(:remove_const, "JAFoo") }

      it "adds new declared accessor fields" do
        Foo.class_eval { jsonb_accessor :data, inventory: :boolean }
        instance = Foo.new
        instance.title = "1.0"
        expect(instance).to respond_to(:inventory)
        expect(instance.title).to eq("1.0")
      end

      it "rewrites the type definition from the super class" do
        Foo.class_eval { jsonb_accessor :data, title: :decimal }
        instance = Foo.new
        instance.title = "1.0"
        expect(instance.title).to eq(1.0)
      end
    end
```

Note the remove const is only becuse of stub_const being called twice. Internally we create a class prefixed with JA + class_name to hold some metadata. This is only a warning and shouldn't affect an environment where you aren't redefining the same class multiple times. I couldn't get an exception to be raised.

**Comment by jhirn** [comment]
@boriscy hey willing to reopen if you can provide a broken test. 

Thanks again for your input!

**Comment by boriscy** [comment]
Hi I have created a fork and added some tests but could not recreate the Error (https://github.com/boriscy/jsonb_accessor).
I work on a project https://github.com/bonsaiERP/bonsaiERP and I have changed `hstore_accessor` to `jsonb_accessor`, the models are **Movement** and **Income**, anyway I have found a way not to raise the exception with some changes. I will try to reproduce the error in my fork https://github.com/boriscy/jsonb_accessor.

Thanks
