### ISSUE TITLE
Using joins for queries raises PostgreSQL error

### ISSUE THREAD

**Issue by boriscy** [devmynd/jsonb_accessor#40]
When using joins for a query it uses the jsonb attributes as part of the query, for example try this
```ruby
Product.includes(:product_category).joins(:product_category).first
```
and you will get a PostgreSQL error.
I have some complicated queries that needed to use **joins** to eager load but have tried with newer version of ActiveRecord and it doesn't need any more, anyway I think should report this.

**Comment by hadees** [comment]
I think this is a duplicate of #33
