### ISSUE TITLE
Namespaced models raise NameError: wrong constant name

### ISSUE THREAD

**Issue by favour121** [devmynd/jsonb_accessor#46]
![image](https://cloud.githubusercontent.com/assets/4352849/14582521/45fa16be-03ff-11e6-90ed-ab7ceb55b448.png)

**Comment by jhirn** [comment]
Hey @favour121. Thanks for reporting this issue! 

Can you provide some sample code to recreate the issue? Can't say I've seen this before.

**Comment by crismali** [comment]
Closing until more information can be provided.
