### ISSUE TITLE
JASettings warnings in delayed_jobs worker

### ISSUE THREAD

**Issue by homerlex** [devmynd/jsonb_accessor#49]
I'm getting tons of the following warnings when running my delayed_jobs worker (jobs:work task).  I'm using Rails 5.0 and jsonb_accessor 0.3.3

```
/opt/ruby/lib/ruby/gems/2.3.0/gems/jsonb_accessor-0.3.3/lib/jsonb_accessor/class_builder.rb:40: warning: already initialized constant JsonbAccessor::JAModAModBKidClazz::JASettings
/opt/ruby/lib/ruby/gems/2.3.0/gems/jsonb_accessor-0.3.3/lib/jsonb_accessor/class_builder.rb:40: warning: previous definition of JASettings was here
```

These warning continue to appear every few seconds even if there are not jobs being processed.

My model class defines the accessors as:

```
jsonb_accessor :settings,
                   account_last_activity: :date_time,
                   contact_last_activity: :date_time,
                   lead_last_activity: :date_time
```

Its probably work noting that the class that defines the accessors is derived from another class (which does not define any jsonb_accessor (using STI).  The class structure looks like.

```
module ModA
  class ParentClazz< ActiveRecord::Base
     ...
  end
end

module ModA::ModB
  class KidClazz< ModA::ParentClazz
    jsonb_accessor :settings,
                   date_a: :date_time,
                   date_b: :date_time,
                   date_c: :date_time
  end
end

```

**Comment by crismali** [comment]
It looks like something about how those workers are set up causes either `jsonb_accessor` to get called multiple times. Probably something weird with the autoloader, but I'm not 100% sure.

**Comment by homerlex** [comment]
Still not sure why it only happens in the jobs:work task but it stems from having a has_many in a model that references the KidClazz like:

`has_many :kids, class_name: ModA::ModB::KidClazz`

**Comment by crismali** [comment]
Are `ActionDispatch::Reloader` (for versions of Rails lower than 5) or `ActiveSupport::Reloader` loaded in the worker?

**Comment by homerlex** [comment]
Yep, Delayed::Worker is calling reload! each time after it sleeps (between looking to jobs to process).  This is what the reload! method looks like:

```
    def self.reload_app?
      defined?(ActionDispatch::Reloader) && Rails.application.config.cache_classes == false
    end

    def reload!
      return unless self.class.reload_app?
      ActionDispatch::Reloader.cleanup!
      ActionDispatch::Reloader.prepare!
    end
```

This would explain why we don't see these warnings in production (where cache_classes == true)

**Comment by crismali** [comment]
We're registering with the reloader to do some clean up. Is it possible that `return unless self.class.reload_app?` is preventing that clean up from happening?

**Comment by homerlex** [comment]
In development `self.class.reload_app?` in `Delayed::Worker` is always true.  Its when `Delayed::Worker` runs `ActionDispatch::Reloader.cleanup!` that we see the warnings.

**Comment by crismali** [comment]
@homerlex Sorry, I lost the thread on this one. 

The features associated with all of this constant management have been removed. Looking at the code you provided again, I think you can get rid of these warnings by upgrading to the most recent beta version. I think you'd just need to change `:date_time` to `:datetime`, but [here's a more complete upgrade guide if you need it](https://github.com/devmynd/jsonb_accessor/blob/master/UPGRADE_GUIDE.md).

Sorry again about the lateness, but I hope that helps 👍
