### ISSUE TITLE
Puzzling Namespace Collision in Rspec

### ISSUE THREAD

**Issue by cheeseandpepper** [devmynd/jsonb_accessor#51]
First, great gem. I've been looking for something like this and it will be super helpful. 👍 

In implementing this, I came across strange behavior. Consider this class in my application.

```
class ChannelJob
  module Helpers
    class MissingAttrError < StanardError; end
  end
end
```

In this gem we have...
```
module JsonbAccessor
  module Helpers
  end
end
```

The only similarity is that we both have a nested module called `Helpers`, but still, both with different top level namespaces.

Here is the spec for testing `ChannelJob::Helpers`

```
require 'rails_helper'

describe ChannelJob::Helpers do
  class BadTestWorker
    include Sidekiq::Worker
    include ChannelJob::Helpers
  end

  class GoodTestWorker
    include Sidekiq::Worker
    include ChannelJob::Helpers
    attr_reader :channel_job

    def initialize(channel_job)
      @channel_job = channel_job
    end
  end

  let!(:channel_job) { create(:channel_job) }
  let(:args) { [] }

  shared_examples "an erring job" do
    it 'will raise an exeption if the channel job attr does not exist' do
      expect { BadTestWorker.new.send(command, *args) }
        .to raise_error(ChannelJob::Helpers::MissingAttrError)
    end

    it 'will raise an exception even if set up correctly but not present' do
      expect { GoodTestWorker.new(nil).send(command, *args) }
        .to raise_error(ChannelJob::Helpers::MissingAttrError)
    end
  end

  context '#finish_job' do
    it_behaves_like 'an erring job' do
      let(:command) { :finish_job }
    end

    it 'will call the correct method if set up correctly and present' do
      binding.pry
      expect(ChannelJob)
        .to receive(:worker_checkin)
        .with(channel_job.id, :finished, log: 'finished job')
      GoodTestWorker.new(channel_job).finish_job
    end
  end

  context '#repeat_job' do
    let(:args) { ['testing...'] }
    let(:jid) { 1234 }

    it_behaves_like 'an erring job' do
      let(:command) { :repeat_job }
    end

    it 'will call the correct method if set up correctly and present' do
      expect(GoodTestWorker)
        .to receive(:perform_in)
        .with(0, channel_job.args)
        .and_return(jid)
      expect(ChannelJob)
        .to receive(:worker_checkin)
        .with(channel_job.id, :repeated, log: 'testing...', jid: jid)
      GoodTestWorker.new(channel_job).repeat_job(*args)
    end
  end
end
```

Now here's the funky part. When running the specs, I get this:

```
NameError:
       uninitialized constant JsonbAccessor::Helpers::MissingAttrError
```

Notice that the `MissingAttrError` is a subclass of my own `ChannelJob::Helpers` and has nothing to do with `JsonbAccessor`.  In fact, none of this is related to jsonb_accessors.  I've implemented that somewhere completely different.  

When I pry into the spec and type `ChannelJob::Helpers` it returns `JsonbAccessor::Helpers`

Similarly, when I type in `BadTestWorker.ancestors` I get
`[BadTestWorker, JsonbAccessor::Helpers, Sidekiq::Worker, etc etc]`  Here I would expect my `ChannelJob::Helpers` to be in there because I am including it in the `BadTestWorker` class.

I was able to circumvent this issue by adding 
```
require 'channel_job'
require 'channel_job/helpers'
```
at the top of my spec. Not ideal, but it seems to "set things straight again."

And the good news is that when I invoke a real worker that includes `ChannelJob::Helpers`, I am able to raise `ChannelJob::Helpers::MissingAttrError`

Anyways, I'm not even sure if this is a bug with this gem, but I wanted to bring it to your attention, and would especially like to understand why this is happening. Any ideas?

**Comment by crismali** [comment]
This looks more like something weird with RSpec to me, but we'll cut a new release at some point soon (hopefully today or tomorrow) that should address this. Also, I'm hoping to get v1.0 out soon which also shouldn't have this problem (since there won't be a `Helpers` module in the gem any more).
