### ISSUE TITLE
Non-typed fields in jsonb_accessor

### ISSUE THREAD

**Issue by marclennox** [devmynd/jsonb_accessor#53]
It seems that with recent changes to support Rails 5, I can no longer use non-typed fields in a jsonb_accessor declaration, nor can I bypass jsonb_accessor to store additional fields in the same jsonb column that I don't want "managed" by jsonb_accessor.

Basically I want to store a hash as a sub-field in a jsonb_accessor field, but can't seem to do this anymore.

Is this a known issue?

**Comment by crismali** [comment]
The rails-5 branch was for the 1.0 beta release which has a different API than the 0.X releases. We have some information about `:value` types in the [upgrade guide](https://github.com/devmynd/jsonb_accessor/blob/v1.0.0.beta.1/UPGRADE_GUIDE.md).

**Comment by crismali** [comment]
No problem, glad it worked out :)
