### ISSUE TITLE
JsonbAccessor::TypeHelper::UnknownType

### ISSUE THREAD

**Issue by USvER** [devmynd/jsonb_accessor#54]
When i try to define attribute with array syntax like this
```
jsonb_accessor :capabilities,
    spaceFree: [:integer],
    spaceTotal: [:integer]
```
i'm getting `JsonbAccessor::TypeHelper::UnknownType`

**Comment by crismali** [comment]
@USvER you appear to be using the 0.X version of the gem, so if you want to define integer fields you put `jsonb_Accessor :capabilities, spaceFree: :integer`. 

If you're newly adding Jsonb Accessor to a project I'd highly recommend that you use the 1.0 beta. Then the syntax you're currently using will work to define a plain integer field. (If you're trying to define a field that's an array of integers you would use `[:integer, array: true]`)

**Comment by USvER** [comment]
@crismali how to use beta version? use it from git branch?

I want to use [:integer, limit: 8] to define bigint.

**Comment by crismali** [comment]
`gem "jsonb_accessor", "1.0.0.beta.1"` should do the trick.

**Comment by USvER** [comment]
Thanks! That worked!

**Comment by crismali** [comment]
Awesome :)
