### ISSUE TITLE
default values not working as expected?

### ISSUE THREAD

**Issue by stebo** [devmynd/jsonb_accessor#57]
First of all: awesome gem and appreciate the work you are doing here!

Since the last update it is possible to set default values like
```ruby
jsonb_accessor :data,
title: [:string, default: "Untitled"]
```
I figured out that this is somehow ONLY working on object initialization and that default values are not being saved if they are not manually changed:

```ruby
b = Book.new
b.title
=> "Untitled"
b.save
b = Book.last
b.title
=> nil
```
Only if I change the value it will be saved in the DB:

```ruby
b = Book.new
b.title
=> "Untitled"
b.title = "New title"
=> "New title"
b.save
b = Book.last
b.title
=> "New title"
```

Thats the first thing I am wondering about, why are they not saved if unchanged?

Than, I **would** understand the default functions as follows: 

Whenever I request a jsonb_accessor attribute which has a default value this default value should be returned if no other value is set. So if Book.title is actually nil or there is no entry for title in the jsonb it would return the default value
```ruby
b = Book.last
b.data
=> {}
b.title
=> "Untitled"
```
That would also have on big advantage: At anytime you can add new attributes to your Model (like Book.background_color, Book.headline_size) and by defining default values for it, they are instant accessible in your application overall even without writing them to the DB.
In the current version Book.background_color would return nil, even if "default" is set...

I am really interested in your opinion on this, maybe I do not unterstand the right usage!

**Comment by adambedford** [comment]
+1 I've run into this too. Not sure if its my misunderstanding of how default values on `attribute` are supposed to behave, but I understood it the way you described.

**Comment by crismali** [comment]
I should have time to play around with this soon (Things have been hectic with the holidays and all).

**Comment by stebo** [comment]
@crismali any news about this? would love to support but I am currently not sure where would be the best place to include this without breaking other stuff

**Comment by DavidHooper** [comment]
Fixing this right now.

Issue is the jsonb_attribute isn't updated on initialisation to reflect the current state of the scoped attributes.

**Comment by DavidHooper** [comment]
Alright, need some help with this. 

I've added some code to sync the `jsonb_attribute` with each of the virtual attributes. I'm doing this in `after_initialization`. This however causes the `jsonb_attribute` to be in a dirty state on creation. 

Any thoughts?

**Comment by crismali** [comment]
@DavidHooper I'll take a look at #67. I'd like to make sure there aren't any weird edge cases (in my experience with previous iterations of this sort of feature, there always are). That being said, leaving the object in dirty state isn't ideal. It might be possible to adjust what's in there slightly to avoid that, but off-hand I don't have a solution :)

**Comment by crismali** [comment]
We've added better support for defaults in the `1.0.0.beta.3` release. I'm going to close this, but if things are still weird I'm happy to reopen it 👍

**Comment by DavidHooper** [comment]
Can you point me in the direction of where this has been implemented?

I'm toying around with some stuff on my own projects and would love to see how you've done it.

**Comment by crismali** [comment]
Sure thing. Here's the [main chunk of code](https://github.com/devmynd/jsonb_accessor/blob/v1.0.0.beta.3/lib/jsonb_accessor/macro.rb#L38-L48) that takes care of this. Essentially, instead of passing each jsonb accessor defined field's default value through to `attribute`, we built a hash out of them (mapped to store keys) and made that hash the default value for the jsonb column itself.

**Comment by DavidHooper** [comment]
I like this 👍 

I accidentally came across the same solution this morning when I was toying around with deeply nested hashes. Writing it from scratch I made the hash first with default values to view if it was plausible.
