### ISSUE TITLE
Strange behaviour when updating an object twice subsequently in jobs

### ISSUE THREAD

**Issue by hundsim** [devmynd/jsonb_accessor#58]
I have two email jobs that are run subsequently. The jobs both update a shared object (Event), on different jsonb-attributes. 

    class Event < ApplicationRecord
      jsonb_accessor :data,
      response_code_host: :integer,
      response__code_guest: :integer
    end

But only one attribute persists its value, the one that is updated last. It's if like Rails cannot see the difference between different attribute-names and just over-writes the first saved one with new key and value.

I cannot reproduce this in the console, it only happens in ActiveJob.

**Comment by crismali** [comment]
When you say the object is shared, do you mean the Ruby instance of it or that each job pulls the record out of the database?

**Comment by hundsim** [comment]
I've tried both to pass the object instance to the jobs (and let Rails serialize/deserialize through GobalID) and pass the object ID to the jobs (and "manually" find the object from the database before updating).

**Comment by crismali** [comment]
Jsonb Accessor is just saving whatever hash it has at the time into the column. A few workarounds might be:

- execute the jobs serially
- just before saving the record in either job, pull it out of the database again and merge the jsonb hashes before saving
- update the record using [`jsonb_set`](https://www.postgresql.org/docs/9.5/static/functions-json.html) (we have an issue open for this [here](https://github.com/devmynd/jsonb_accessor/issues/36) to integrate it with Jsonb Accessor, but it hasn't happened yet)

**Comment by hundsim** [comment]
- Number two didn't work unfortunately.
- Number three is for PG 9.5 if I got it right, and I'm not on really there yet..
- I'd love to give number one a try, but don't find any resources how to tell ActiveJob to run the jobs serially. If you know where I could read up on the subject I'd be very happy :)

(Thanks for your rapid reply and an awesome gem!)

**Comment by undergroundwebdesigns** [comment]
@hundsim this sounds like a classic race condition bug, which is easy to run into with simultaneous background workers (I've personally experienced in numerous times). It's probably not limited to json keys either, you'd probably see the same thing if you were updating actual columns in the DB. Coding both your jobs to use pessimistic DB locking (http://guides.rubyonrails.org/active_record_querying.html#pessimistic-locking) of the record you're trying to update should fix it. That will make sure that each job has the latest version of the record before it updates it, and won't allow another process to simultaneously update it. Another slightly more involved solution is to use a mutex, e.g. https://github.com/kenn/redis-mutex.

This doesn't sound like a bug in `jsonb_accessor` though, maybe this issue should be closed?

**Comment by hundsim** [comment]
Thanks a bunch @undergroundwebdesigns! You seem to have been spot on 😬
