### ISSUE TITLE
undefined method `each' for "{}":String

### ISSUE THREAD

**Issue by vincentkedison** [devmynd/jsonb_accessor#59]
in model
```
jsonb_accessor :data,
    first_name: :string,
    last_name: :string,
    slug: :string
```

raise this error 

> undefined method `each' for "{}":String

```
def new
    @card = Card.new
end
```

**Comment by smyrgl** [comment]
I suspect your migration is setting the default to '{}' instead of {}.

**Comment by crismali** [comment]
That seems very likely. I'm going to close this, but I'm happy to reopen if there's more information that points to a different issue.
