### ISSUE TITLE
Does the "default" option work?

### ISSUE THREAD

**Issue by hundsim** [devmynd/jsonb_accessor#62]
I've set default values as per below. I assumed they would be set when an object is instantiated, but after creating an object and calling the jsonb attributes - only `nil` is returned.

	class AccountSetting < ApplicationRecord
		jsonb_accessor :data,
		    last_web_session: 			:datetime,
		    web_session_count: 			[:integer, default: 0],
		    title:                              [:string, default: "Untitled"]

I had wished that I could directly do this `account_setting.web_session_count += 1` , but perhaps I have misunderstood how setting `default` is supposed to work?

**Comment by hundsim** [comment]
I missed that an issue already was open on this.

**Comment by krnjn** [comment]
@hundsim -- did you find a resolution to this? As far as I can tell, this is still an issue.
