### ISSUE TITLE
Query for IS NOT NULL

### ISSUE THREAD

**Issue by adambedford** [devmynd/jsonb_accessor#65]
Chances are I'm missing this somewhere in the docs but is there a way to check if a field IS NOT NULL?

Trying `jsonb_where(:data, date: "IS NOT NULL")` results in literal use of "IS NOT NULL" as a string. Trying `!nil` naturally results in a check for `true`.

**Comment by crismali** [comment]
To my knowledge, `not` queries aren't currently supported. I don't think it would take too much work to get them going though.

**Comment by crismali** [comment]
@adambedford We've added a few [scopes](https://github.com/devmynd/jsonb_accessor#scopes) to address this in version `1.0.0.beta.3`. Hope they help!

**Comment by adambedford** [comment]
@crismali Wonderful, thank you!
