### ISSUE TITLE
How to accept params in controller?

### ISSUE THREAD

**Issue by domi91c** [devmynd/jsonb_accessor#66]
I have the gem working with about 30 fields on a Form model.
```
class Form < ApplicationRecord
  jsonb_accessor :fields,
                 salutation: :string, # personal info
                 first_name: :string,
                 last_name: :string,
                 birthday: :string,
                 marital_status: :string,
                 number_of_dependants: :string,
                 first_time_owner: :string,
                 spouse_deal: :string,
                 phone_cell: :string, # contact info
                 phone_home: :string,
                 phone_work: :string,
                 email: :string,
                 ...
 end
```
```
  <%= form_for(form) do |f| %>
      <%= render 'layouts/errors', model: form %>


      <h2>Personal Info</h2>

      <%= f.label :salutation, 'Salutation', class: 'control-label' %>
      <%= f.select :salutation, options_for_select(%w(Mr. Ms. Mrs. Dr.)),
                   {}, {class: "form form-group form-control"} %>

      <%= f.label :first_name, 'First Name', class: 'control-label' %>
      <%= f.text_field :first_name, class: 'form-control' %>

      <%= f.label :last_name, 'Last Name', class: 'control-label' %>
      <%= f.text_field :last_name, class: 'form-control' %>

      <%= f.label :birthday, 'Date of Birth', class: 'control-label' %>
      <br>
      <%= f.date_select :birthday, class: "form-control" %>

      <%= f.label :marital_status, 'Marital Status', class: 'control-label' %>
      <%= f.text_field :marital_status, class: 'form-control' %>

      <h2>Contact Info</h2>

      <%= f.label :phone_cell, 'Cell Phone', class: 'control-label' %>
      <%= f.text_field :phone_cell, class: 'form-control' %>

      <%= f.label :phone_home, 'Home Phone', class: 'control-label' %>
      <%= f.text_field :phone_home, class: 'form-control' %>

      <%= f.label :email, 'Email', class: 'control-label' %>
      <%= f.text_field :email, class: 'form-control' %>

      ...

      <%= f.submit %>    

<% end %>
```
I've setup the above form and I'm confused about how to receive these params in my controller after submitting the form. I'm now not sure if I should have used this gem in the first place, given each field is now a first level method on my Form objects, and the params are not sent in a hash which would be required for all the solutions I've found.

<img width="1440" alt="screen shot 2017-03-08 at 8 05 47 pm" src="https://cloud.githubusercontent.com/assets/5838941/23743218/cc32d3ea-047d-11e7-9dae-f6dc06ada373.png">

I can hard code each field into the form_params method of my controller, but I'll eventually have many different form views each requiring different fields, so that isn't going to work. Any advice on how I should set this up?

**Comment by crismali** [comment]
It sounds like you're after dynamic fields in your form and being able to accept dynamic parameters in your controller, is that correct? If so, jsonb_accessor probably isn't the right tool for the job. 

If you just don't want to duplicate the field names in your `form_params` method, you could pull your attributes hash into a constant in the model and then call `keys` on that and pass it into strong params. Right now there isn't a way to get at the meta data you've passed to the `jsonb_accessor` method.

Let me know if that helps!

**Comment by crismali** [comment]
Closing for now, but I'm happy to reopen if we get more information that shows jsonb accessor is the right tool for this particular use case.
