### ISSUE TITLE
ArgumentError: Passing string to define a callback is not supported

### ISSUE THREAD

**Issue by draconiandev** [devmynd/jsonb_accessor#68]
Hi! Just starting out with the gem. But console is throwing me this error.

```
ArgumentError: Passing string to define a callback is not supported. See the `.set_callback` documentation to see supported values.
from /home/p150/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.0.beta1/lib/active_support/callbacks.rb:282:in `build'
```

I am trying to use
```ruby
jsonb_accessor :data, title: :string
```

Using Ruby 2.4.0, Rails 5.1.0beta1 and 1.0.0.beta.2 of this gem. Any help?

**Comment by crismali** [comment]
My guess is that it's something to do with the Rails 5.1 beta. It's odd though, because it looks like the closest we get to passing a string as a callback is when we're naming our custom scopes. We'll get ActiveRecord 5.1 beta into the test suite soon and then we'll know more.

**Comment by draconiandev** [comment]
Maybe this stack trace helps.
```
Exception: ArgumentError: Passing string to define a callback is not supported. See the `.set_callback` documentation to see supported values.
--
0: /home/p150/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.0.beta1/lib/active_support/callbacks.rb:282:in `build'
1: /home/p150/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.0.beta1/lib/active_support/callbacks.rb:674:in `block in set_callback'
2: /home/p150/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.0.beta1/lib/active_support/callbacks.rb:673:in `map'
3: /home/p150/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.0.beta1/lib/active_support/callbacks.rb:673:in `set_callback'
4: /home/p150/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activemodel-5.1.0.beta1/lib/active_model/callbacks.rb:144:in `block in _define_after_model_callback'
5: /home/p150/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/jsonb_accessor-0.3.3/lib/jsonb_accessor/macro.rb:56:in `_initialize_jsonb_attrs'
6: /home/p150/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/jsonb_accessor-0.3.3/lib/jsonb_accessor/macro.rb:18:in `jsonb_accessor'
```

**Comment by crismali** [comment]
Based on your stack trace, it looks like you're actually on version 0.3.3 of jsonb_accessor. Maybe your Gemfile isn't explicit enough? `gem "jsonb_accessor", "1.0.0.beta.2"` should do the trick.

**Comment by draconiandev** [comment]
Stupid me! Thank you.

**Comment by crismali** [comment]
No worries!

**Comment by draconiandev** [comment]
Hi @crismali Sorry to bother you again. Is there any way to make store_key to take from a method?

Something like this:

```ruby
class Post < ApplicationRecord
  jsonb_accessor :data, title: [:string, store_key: some_method]

  def some_method
    #returns a parameterized symbol
  end
```

**Comment by crismali** [comment]
Right now there isn't a way to do that (I believe it would break the scopes, or at least make them pretty useless). What's your use case?

**Comment by draconiandev** [comment]
Something like this. Say I have a few writers who publish articles on various platforms. Each of these platforms have a title and a body in an article, but they are named differently. Eg: One guy might say body and the other content. So to aggregate them, I will be fetching the json through the api and saving it in the data attribute. So before saving, I would like them to be converted for consistency. Or, look up using a template model which maps the attributes to the api's json key.

The other way can be to save the raw data as it is and create another model instance(say processed article) and use that.

These might be a totally wrong ways to do this. I am ready to explore other options.

**Comment by crismali** [comment]
With jsonb accessor, you could do something with [STI](https://github.com/devmynd/jsonb_accessor#single-table-inheritance) where you just specify the particular store keys in each subclass. Not sure that's the best approach through. My initial reaction would be to convert all of the json from the different services into a standard format. Probably just stored in regular columns. I'd also probably throw the raw json into a column for triage more than anything else.

**Comment by draconiandev** [comment]
Thanks for the help Micheal. I will try to standardize the format and see how it goes from there. Appreciate it.

**Comment by crismali** [comment]
No problem!
