### ISSUE TITLE
Validations not working beta3

### ISSUE THREAD

**Issue by rognvaldur-msn-com** [devmynd/jsonb_accessor#71]
**in a model**
 jsonb_accessor :properties,
      zoom: :integer
  validates_numericality_of :zoom, greater_than_or_equal_to: 0, less_than_or_equal_to: 22 unless self.zoom.nil?
throws
undefined method `zoom' for #<Class:0x12171a68>

**Comment by crismali** [comment]
There's an issue with how the validation is declared.
```ruby
jsonb_accessor :properties, zoom: :integer
validates_numericality_of :zoom, greater_than_or_equal_to: 0, less_than_or_equal_to: 22, if: :zoom? 
```

You need `unless`/`if` to be a symbol as well as what you pass to it (in this case, `:zoom?`). You can pass any symbol there as long as it's an instance method on the object.
