### ISSUE TITLE
:default => false does not save to jsonb column

### ISSUE THREAD

**Issue by zokioki** [devmynd/jsonb_accessor#74]
If you create an object whose jsonb_accessor attribute has a default value of `false` that attribute will not be saved in the jsonb column.

To reproduce:

```ruby
class Product < ActiveRecord::Base
  jsonb_accessor :data,
    color: [:string, default: 'blue']
    on_sale: [:boolean, default: false]
end

product = Product.create
product.data
# => { color: 'blue' }
```

Expected output:

```ruby
product.data
# => { color: 'blue', on_sale: false }
```

**Comment by crismali** [comment]
[Released!](https://github.com/devmynd/jsonb_accessor/releases/tag/v1.0.0.beta.4)
