### ISSUE TITLE
ActiveModel::MissingAttributeError when using select

### ISSUE THREAD

**Issue by oliverx0** [devmynd/jsonb_accessor#76]
Hello, I am sorry if this issue has been raised before or fixed in the latest version (I took a quick look at the commits and did not find it).

I have a model in Rails where one of the columns is a jsonb hash that uses jsonb accessor. When I try to make a query using select on specific attributes, if the jsonb accessor column is not included, the error ActiveModel::MissingAttributeError is raised. 

Example:

If the columns of the Model user are first_name, last_name, and data.

jsonb_accessor :data,
     gender: :string

If I do User.where(first_name: 'Oliver') I get the users without a problem. If I do User.select(:last_name).where(first_name: 'Oliver') then it raises the error. 

If I do User.select(:last_name, :data).where(first_name: 'Oliver') then it does not raise the error.

Thank you for your help!

**Comment by oliverx0** [comment]
I believe the error might have something to do with that is described in this answer: http://stackoverflow.com/questions/6820156/activemodelmissingattributeerror-occurs-after-deploying-and-then-goes-away-aft

**Comment by oliverx0** [comment]
Created a pull request: https://github.com/devmynd/jsonb_accessor/pull/77

**Comment by crismali** [comment]
[Released!](https://github.com/devmynd/jsonb_accessor/releases/tag/v1.0.0.beta.5)
