### ISSUE TITLE
Support ActiveRecord 5.1.x

### ISSUE THREAD

**Issue by aliuk2012** [devmynd/jsonb_accessor#79]
Hi,

Any chance you could add support for activerecord 5.1.1? I'm trying to update my rails application from rails 5.0.2 to 5.1.1 and this gem is causing problems with updating.

I have forked it and bumped the gemspec activerecord version from 5.0 to 5.1. This is the right approach? I'm happy to submit a Pull request if it would help move things along.

Many Thanks
Alistair

**Comment by jhirn** [comment]
Hey Alistair!

What problem are you having exactly with upgrading?

**Comment by aliuk2012** [comment]
It is failing because it says the gem requires active record 5.0.

**Comment by aliuk2012** [comment]
```bash
$ bundle update
Fetching gem metadata from https://rubygems.org/.............
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies......
Bundler could not find compatible versions for gem "activerecord":
  In Gemfile:
    jsonb_accessor (~> 1.0.0.beta.6) was resolved to 1.0.0.beta.6, which depends on
      activerecord (>= 5.0)

```

**Comment by noniq** [comment]
I'm using this gem in a project with Rails / ActiveRecord 5.1.2 without any problems. jsonb_accessor’s gemspec states it depends on activerecord `5.0` *or greater*, so this is expected to work. Are you sure there aren’t any other gems in your setup causing bundler to fail?

**Comment by crismali** [comment]
@aliuk2012 Could you provide all of the gems from your `Gemfile.lock` that depend on ActiveRecord and the versions of ActiveRecord they depend on?

**Comment by matissg** [comment]
@aliuk2012  I'm using the gem on AR 5.1.3. and no issues so far - CRUD works as expected.

**Comment by crismali** [comment]
@aliuk2012 Could you provide your `Gemfile.lock`? It will make this issue much easier to figure out.

Also, I've just bumped the test suite to run against ActiveRecord 5.1.3 and had no problem running the tests against it so it looks to me like this is some other dependency that's causing the problem. I'm happy to continue helping you with this, but I'm going to close the issue so anyone who is just browsing the issues doesn't think that ActiveRecord 5.1 isn't supported.
