### ISSUE TITLE
Use symbol instead of string when defining callback

### ISSUE THREAD

**Issue by likelazyeyes** [devmynd/jsonb_accessor#84]
Passing string to define callback is removed in Rails 5.1 

In the rails repo see line 284, it raises this error on rails 5.1
https://github.com/rails/rails/blob/master/activesupport/lib/active_support/callbacks.rb

It is similar issue example:
https://github.com/swanandp/acts_as_list/pull/192

I didn't understand how to fix it, i have tried converting strings to symbol

Anybody can fix this?

**Comment by temkin** [comment]
@likelazyeyes  any news on this issue?

**Comment by crismali** [comment]
@likelazyeyes @temkin What versions of the Jsonb Accessor and ActiveRecord are you using? I just updated the project to run the tests against ActiveRecord 5.1.3 and everything was green.

**Comment by temkin** [comment]
@crismali my bad, latest version 1.0.0.beta.7 works like a charm!

**Comment by crismali** [comment]
@temkin No problem!

**Comment by likelazyeyes** [comment]
I was tested on 5.1.2 and downgraded to 5.0.1 again. This week i try upgrade again. Which branch should i use?

**Comment by crismali** [comment]
@likelazyeyes the most recent release is v1.0.0
